#!/bin/bash

### configure the project to use this custom hooks directory
# git config core.hooksPath .githooks

# Get list of staged files
files=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(cpp|cc|h|hpp)$')

if [ -n "$files" ]; then
    # Format all staged files
    echo "Formatting staged files..."
    for file in $files; do
        clang-format -i "$file"
        git add "$file"
    done
fi

exit 0
